services:
  db:
    image: postgres:17.5-alpine3.22
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-dompetku
    volumes:
      - ./postgres:/var/lib/postgresql/data 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
